version: "3.7"

services:
  db:
    image: postgres:13
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: moneytransfer
      POSTGRES_USER: moneytransfer
      POSTGRES_DB: moneytransfer